package com.diamondq.common.i18n;

import java.util.Locale;
import java.util.ResourceBundle;

import org.checkerframework.checker.nullness.qual.Nullable;

/**
 * This interface describes enums that are used for I18N messages. They are normally generated by the i18n-maven-plugin.
 */
public interface MessagesEnum {

  /**
   * Return a key representing the message. This key can be looked up in the provided ResourceBundle
   * 
   * @return the key
   */
  public String getCode();

  public ResourceBundle getBundle(Locale pLocale);

  public default I18NString with(@Nullable Object @Nullable... pParams) {
    return new I18NString(this, pParams);
  }
}
