package com.diamondq.common.i18n;

import org.jspecify.annotations.Nullable;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 * This interface describes enums that are used for I18N messages. They are normally generated by the
 * i18n-maven-plugin.
 */
public interface MessagesEnum {

  /**
   * Return a key representing the message. This key can be looked up in the provided ResourceBundle
   *
   * @return the key
   */
  String getCode();

  ResourceBundle getBundle(Locale pLocale);

  default I18NString with(@Nullable Object @Nullable ... pParams) {
    return new I18NString(this, pParams);
  }
}
